/* eslint-disable @next/next/link-passhref */
/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Discord() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Soetch's Discord</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="py-3">
        <div
          style={{
            display: "flex",
            justifyContent: "center",
          }}
        >
          <span className={styles.logo}>
            <a
              href="https://soetch.vercel.app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <span className={styles.logo}>
                <Image src="/soetch.svg" alt="Soetch Logo" width={150} height={38} />
              </span>
            </a>
          </span>
        </div>
      </header>

      <main className={styles.main}>
        <h1 className="text-9xl underline">
          Soetch#8877
        </h1>
      </main>

      <footer className={styles.footer}>
        <div>
        <a
          href="https://github.com/soetch"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image src="/github.svg" alt="Github Logo" width={32} height={32} />
        </a>
        </div>

        <Image src="/line.png" alt="line" width={64} height={32} />

        <div>
        <a
          href="https://twitch.tv/soetch"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image src="/twitch.svg" alt="Twitch Logo" width={32} height={30} />
        </a>
        </div>

        <Image src="/line.png" alt="line" width={64} height={32} />

        <div>
        <a
          href="https://twitter.com/soetch"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image src="/twitter.svg" alt="Twitter Logo" width={32} height={30} />
        </a>
        </div>

        <Image src="/line.png" alt="line" width={64} height={32} />

        <div>
        <a
          href="/discord"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Link href="/discord">
            <Image src="/discord.svg" alt="Discord Logo" width={32} height={30} />
          </Link>
        </a>
        </div>
      </footer>
    </div>
  )
}
